### ISSUE TITLE
Support lib overlays

### ISSUE THREAD

**Issue by lovesegfault** [Infinisil/nixus#11]
> infinisil │ It's tricky because lib itself is used to evaluate modules                                                                                                                                                                
> infinisil │ But if those very modules define lib overlays, then that gives a bit of infinite recursion

**Comment by Infinisil** [comment]
This might be nicely possible by adding an argument to the main Nixus function, so deployments files look like
```nix
import /path/to/nixus {} {
  nodes.foo = ...;
}
```

In this extra argument we could then have a lib overlays option:
```nix
import /path/to/nixus {
  libOverlays = [
    (self: super: { myFunction = "foo"; })
  ];
} {
  nodes.foo = ...;
}
```

This extra argument would also allow future extra arguments if they are ever needed (which is if they can't be controlled from the module system itself).

**Comment by Infinisil** [comment]
This can now be done since https://github.com/Infinisil/nixus/commit/69462cdd201a938a2f3e72840bbd7d3c96a795a1 with

```nix
import /path/to/nixus {
  libOverlay = self: super: {
    myValue = 10;
  };
} {
  nodes = ...;
}
```
