### ISSUE TITLE
Setting the system version read by Nix in /etc/os-release and nixos-version

### ISSUE THREAD

**Issue by berbiche** [Infinisil/nixus#15]
I switched from NixOps to Nixus to deploy my local machine and thought I would share the outcome of a discussion from the Nix Matrix channel.

When using a custom nixpkgs outside of the channels, some files are going to be missing that allows nixpkgs to determine its revision.
The required files are only bundled in the channel (https://github.com/NixOS/nixpkgs/blob/d3c2247b77924818622320f9dc790f4403afc6f0/nixos/lib/make-channel.nix).

Upon building the system, the version would default to "pre-git" instead of the hash.
`nixos-version` would then fail to show the correct revision.

In the case of using Niv, the workaround is simple:

``` nix
let
  sources = import ./nix/sources.nix;
  nixus = import sources.nixus;

  nixpkgs = sources.nixpkgs;
  nixpkgsRev = builtins.substring 0 8 nixpkgs.rev;
in
nixus ({ ... }: {
  defaults = { ... }: {
    inherit nixpkgs;
    configuration = { lib, ... }: {
      # The two following lines are what we are interested by
      system.nixos.revision = nixpkgs.rev;
      system.nixos.versionSuffix = ".${nixpkgsRev}";
    };
  };
})
```

The result:

``` console
$ cat /etc/os-release
NAME=NixOS
ID=nixos
VERSION="20.09.2cd2e726 (Nightingale)"
VERSION_CODENAME=nightingale
VERSION_ID="20.09.2cd2e726"
PRETTY_NAME="NixOS 20.09 (Nightingale)"
LOGO="nix-snowflake"
HOME_URL="https://nixos.org/"
DOCUMENTATION_URL="https://nixos.org/learn.html"
SUPPORT_URL="https://nixos.org/community.html"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
```

``` console
$ nixos-version --revision
2cd2e7267e5b9a960c2997756cb30e86f0958a6b
```

This also has the effect of setting the right string for the grub entry (should also be the case for systemd-boot)

**Comment by Infinisil** [comment]
Cool! Maybe with Flakes becoming the future standard this could be done by Nixus automatically somehow. I'll close this issue since it's not really an issue, but I'll remember it if anybody asks for something like this :)
