### ISSUE TITLE
Alternative to `sudo`

### ISSUE THREAD

**Issue by Infinisil** [Infinisil/nixus#22]
As @cole-h pointed out [here](https://github.com/Infinisil/nixus/commit/89120c2716336ba0328ff0195c0aeffb558199c9#r39535869), there are other ways than `sudo` to get root access, such as [`doas`](https://github.com/Duncaen/OpenDoas). Nixus should not hardcode this to `sudo`.

Nixops supports other ways via a [`privilegeEscalationCommand`](https://github.com/NixOS/nixops/blob/0330ead36be75c0b0f80cf84c227f13380daf414/nix/options.nix#L83-L95) option, we could mirror that.

**Comment by cole-h** [comment]
(That's the wrong `doas` -- Nixpkgs contains https://github.com/Duncaen/OpenDoas)

**Comment by Infinisil** [comment]
Ah thanks! Corrected now

**Comment by bqv** [comment]
Alternatively, since we depend on SSH anyway, why not have a special SSH route/user/command/hatch

**Comment by cole-h** [comment]
Some deployments disallow SSH root logins (`PermitRootLogin=no`), unless there's another system in place for this sort of privilege escalation that I'm overlooking.

**Comment by bqv** [comment]
Well, since nixus is good with ssh keys anyway, I feel like catering for "without-password" machines wouldn't be terrible

**Comment by cole-h** [comment]
It would be a nice addition indeed, but it should not be seen as a substitute for `doas` or `sudo`. I disable SSH root logins for my machines, period. I wouldn't change this just to be able to use nixus.

My takeaway is that both

1) `sudo` alternatives
2) SSH root logins

should be supported, and not only one or the other.

**Comment by Infinisil** [comment]
Now addressed with above PR. And SSH root login already worked :)
