### ISSUE TITLE
Build an image from a configuration that uses secrets

### ISSUE THREAD

**Issue by cpcloud** [Infinisil/nixus#35]
I'm getting a lot of mileage out of `nixus`. I recently moved over to using the secrets feature, which I really like. However, when trying to build an image with one of my system's configurations I can't because the configuration doesn't know about `modules/secrets.nix`.

is there a way to expose that module such that I'd be able to build an image with a configuration?

**Comment by Infinisil** [comment]
Glad you like it!

Not entirely sure what problem you're having though, what commands are you trying that don't work and what's the error?

Maybe you're interested in a command like
```
nix-build nixus-config.nix -A config.nodes.<node>.configuration.system.build.isoImage
```

(note that this requires the `iso-image.nix` module to be added to `imports`)

**Comment by cpcloud** [comment]
@Infinisil Yup. Thanks. I just wasn't aware of the `config.nodes.<node>` attribute. @lovesegfault helped me out on this too. Closing!
