### ISSUE TITLE
unstable nixpkgs update broke nixus (noUserModules)

### ISSUE THREAD

**Issue by etu** [Infinisil/nixus#41]
The short error message is this:
```
error: attribute 'noUserModules' missing

       at /nix/store/2ziv91pi6y3kjgj43xz718haiy4rhbmy-source/lib/modules.nix:305:28:

          304|         builtins.addErrorContext (context name)
          305|           (args.${name} or config._module.args.${name})
             |                            ^
          306|       ) (lib.functionArgs f);
(use '--show-trace' to show detailed location information)
```

Full log with `--show-trace` here: [errorlog.txt](https://github.com/Infinisil/nixus/files/7745922/errorlog.txt)

The cause seems to be this: https://github.com/NixOS/nixpkgs/pull/144094

**Comment by Infinisil** [comment]
Above commit wasn't backwards compatible. https://github.com/Infinisil/nixus/commit/817ef8a9a9e37e9fbf414507daaf8e477640e1c7 should fix this!
