### ISSUE TITLE
Passing extra args to node config

### ISSUE THREAD

**Issue by busti** [infinisil/nixus#56]
I wish to pass extra args to the configuration file of a node. Right now I am doing the following:  
```
nodes.styx = {
  host = "root@styx";
  configuration =
    (import ./configuration.nix { unstable = (unstable.legacyPackages.${system}); });
};
```

However this is quite dirty. In flakes there is the convenient `specialArgs` for accomplishing this.  
Does something similar exist here?

**Comment by infinisil** [comment]
`specialArgs` is not a flake thing, it's a module system thing. It's possible to use it, but not trivial, just added an example: https://github.com/infinisil/nixus/commit/5257be6a58e6093d0ef7540cee1bf764194e72af

**Comment by busti** [comment]
Thanks a lot for sharing, works like a charm :)
