### ISSUE TITLE
mixing nixpkgs versions (pkgs and lib)

### ISSUE THREAD

**Issue by eyJhb** [infinisil/nixus#62]
Currently nixus mixes nixpkgs versions, ie. the one bundled with nixus, and the one used on the host. So e.g. the `lib.version` will be the nixus lib, whereas `pkgs.lib` will be the version that the should be on the host.
E.g. adding the following to the example configuration.nix, will yield in two different versions.

```
  networking.hostId = lib.trace "${lib.version} ${pkgs.lib.version}" "4cf9f4d7";
----- OUTPUT NON-LEGACY
trace: 23.11pre-git 22.05pre-git
------ LEGACY 
trace: 21.11pre-git 21.11pre-git
```

This can cause various issues, that we until now have not really have to deal with too badly.
However, it's possible to fix it by specifying `specialArgs.lib` for the non-legacy `evalConfig` like so.

```patch
diff --git a/modules/options.nix b/modules/options.nix
index 6d8bda8..8a79578 100644
--- a/modules/options.nix
+++ b/modules/options.nix
@@ -62,6 +62,7 @@ let
             };
             evalConfig = import (config.nixpkgs + "/nixos/lib/eval-config.nix") {
               system = nixus.pkgs.system;
+             specialArgs.lib = nixus.extendLib (import (config.nixpkgs + "/lib"));
               modules = [
                 extraConfig
                 {
@@ -71,7 +72,6 @@ let
                   };
                 }
               ];
-              lib = nixus.extendLib (import (config.nixpkgs + "/lib"));
             };
           in evalConfig.type or legacy;
         default = {};
```

I'm not sure what the actual issue is (as far as I can tell, using `specialArgs` shouldn't be needed), or what the best fix for this is. It seems like the current lib argument that is given, is just ignored, as I can delete it and it works just fine.

This is the patch I've used for testing.

```patch
diff --git a/example/configuration.nix b/example/configuration.nix
index 86ce16d..6ebb2df 100644
--- a/example/configuration.nix
+++ b/example/configuration.nix
@@ -9,6 +9,8 @@
   boot.loader.grub.device = "/dev/vda";
   boot.kernelPackages = pkgs.linuxPackages_latest;
 
+  networking.hostId = lib.trace "${lib.version} ${pkgs.lib.version}" "4cf9f4d7";
+
   networking = {
     useDHCP = false;
     nameservers = [ "1.1.1.1" "1.0.0.1" ];
diff --git a/modules/options.nix b/modules/options.nix
index 6d8bda8..2b63cf8 100644
--- a/modules/options.nix
+++ b/modules/options.nix
@@ -62,6 +62,7 @@ let
             };
             evalConfig = import (config.nixpkgs + "/nixos/lib/eval-config.nix") {
               system = nixus.pkgs.system;
+              specialArgs.lib = nixus.extendLib (import (config.nixpkgs + "/lib"));
               modules = [
                 extraConfig
                 {
@@ -71,7 +72,6 @@ let
                   };
                 }
               ];
-              lib = nixus.extendLib (import (config.nixpkgs + "/lib"));
             };
           in evalConfig.type or legacy;
         default = {};
```

**Comment by eyJhb** [comment]
Maybe this could be merged into master, @infinisil . I'm however unsure, if it would break anything. I've been using this since I posted it without any issues. But that doesn't give much in the bigger picture :)

**Comment by infinisil** [comment]
Sounds good to me, I think this might've been the original intention even, feel free to push it!

**Comment by eyJhb** [comment]
I actually think we could remove the legacy thing now, because that might just have been a biproduct of this issue. This should also make so we don't have to bump nixpkgs all the time :D
